calendar_command:
  - text: ${calendar_command_query}
    code: ${calendar_command_query}
    var: ${calendar_command_query:var}
  - text: ${calendar_command_event_find}
    code: ${calendar_command_event_find}
    var: ${calendar_command_event_find:var}
  - text: ${calendar_command_schedule}
    code: ${calendar_command_schedule}
    var: ${calendar_command_schedule:var}
  - text: ${calendar_command_query_tickets}
    code: ${calendar_command_query_tickets}
    var: ${calendar_command_query_tickets:var}
  - text: ${calendar_command_ticket_purchase}
    code: ${calendar_command_ticket_purchase}
    var: ${calendar_command_ticket_purchase:var}

calendar_command_query:
  - text: ${query_command_verb} if ${events_query}
    code: |
      ${events_query}
      Responder.respond(response=${events_query:var})
    var: ${events_query:var}
  - text: ${query_command_verb} if ${calendar_command_query_tickets_item}
    code: |
      ${calendar_command_query_tickets_item}
      Responder.respond(response=${calendar_command_query_tickets_item:var})
    var: ${calendar_command_query_tickets_item:var}

calendar_command_event_find:
  - text: ${calendar_find_event_action} ${event_name}
    code: |
      ${event_name}
      ${calendar_command_event_find:var} = Calendar.find_events(event_name=${event_name:var})
      Responder.respond(response=${calendar_command_event_find:var})
    var: events
  - text: ${calendar_find_event_action} ${event_name} ${event_date_time}
    code: |
      ${event_name}
      ${event_date_time}
      ${calendar_command_event_find:var} = Calendar.find_events(date_time=${event_date_time:var}, event_name=${event_name:var})
      Responder.respond(response=${calendar_command_event_find:var})
    var: events
  - text: ${calendar_find_event_action} ${event_name} ${event_location}
    code: |
      ${event_name}
      ${event_location}
      ${calendar_command_event_find:var} = Calendar.find_events(event_name=${event_name:var}, location=${event_location:var})
      Responder.respond(response=${calendar_command_event_find:var})
    var: events
  - text: ${calendar_find_event_action} ${event_name} ${event_date_time} ${event_location}
    code: |
      ${event_name}
      ${event_date_time}
      ${event_location}
      ${calendar_command_event_find:var} = Calendar.find_events(date_time=${event_date_time:var}, event_name=${event_name:var}, location=${event_location:var})
      Responder.respond(response=${calendar_command_event_find:var})
    var: events

calendar_command_schedule:
  - text: ${schedule_command_action} ${event_name}
    code: |
      ${event_name}
      Calendar.schedule_event(event_name=${event_name:var})
  - text: ${schedule_command_action} ${event_name} ${event_date_time}
    code: |
      ${event_name}
      ${event_date_time}
      Calendar.schedule_event(date_time=${event_date_time:var}, event_name=${event_name:var})
  - text: ${schedule_command_action} ${event_date_time} ${event_name}
    code: |
      ${event_name}
      ${event_date_time}
      Calendar.schedule_event(date_time=${event_date_time:var}, event_name=${event_name:var})
  - text: ${schedule_command_action} ${in|on} ${event_calendar} ${event_name}
    code: |
      ${event_calendar}
      ${event_name}
      Calendar.schedule_event(event_calendar=${event_calendar:var}, event_name=${event_name:var})
  - text: ${schedule_command_action} ${in|on} ${event_calendar} ${event_name} ${event_date_time}
    code: |
      ${event_calendar}
      ${event_name}
      ${event_date_time}
      Calendar.schedule_event(date_time=${event_date_time:var}, event_calendar=${event_calendar:var}, event_name=${event_name:var})
  - text: ${schedule_command_action} ${in|on} ${event_calendar} ${event_date_time} ${event_name}
    code: |
      ${event_calendar}
      ${event_name}
      ${event_date_time}
      Calendar.schedule_event(date_time=${event_date_time:var}, event_calendar=${event_calendar:var}, event_name=${event_name:var})
  - text: ${schedule_command_action} ${event_name} ${event_calendar}
    code: |
      ${event_name}
      ${event_calendar}
      Calendar.schedule_event(event_name=${event_name:var}, event_calendar=${event_calendar:var})
  - text: ${schedule_command_action} ${event_name} ${event_date_time} ${in|on} ${event_calendar}
    code: |
      ${event_name}
      ${event_date_time}
      ${event_calendar}
      Calendar.schedule_event(date_time=${event_date_time:var}, event_name=${event_name:var}, event_calendar=${event_calendar:var})
  - text: ${schedule_command_action} ${event_date_time} ${event_name} ${in|on} ${event_calendar}
    code: |
      ${event_name}
      ${event_date_time}
      ${event_calendar}
      Calendar.schedule_event(date_time=${event_date_time:var}, event_name=${event_name:var}, event_calendar=${event_calendar:var})
  - text: ${schedule_command_action} ${in|on} ${event_calendar} ${event_name} ${event_location}
    code: |
      ${event_calendar}
      ${event_name}
      ${event_location}
      Calendar.schedule_event(event_calendar=${event_calendar:var}, event_name=${event_name:var}, location=${event_location:var})
  - text: ${schedule_command_action} ${in|on} ${event_calendar} ${event_name} ${event_date_time} ${event_location}
    code: |
      ${event_calendar}
      ${event_name}
      ${event_date_time}
      ${event_location}
      Calendar.schedule_event(date_time=${event_date_time:var}, event_calendar=${event_calendar:var}, event_name=${event_name:var}, location=${event_location:var})
  - text: ${schedule_command_action} ${in|on} ${event_calendar} ${event_date_time} ${event_name} ${event_location}
    code: |
      ${event_calendar}
      ${event_name}
      ${event_date_time}
      ${event_location}
      Calendar.schedule_event(date_time=${event_date_time:var}, event_calendar=${event_calendar:var}, event_name=${event_name:var}, location=${event_location:var})

calendar_command_ticket_purchase:
  - text: ${calendar_purchase_action} ${event_ticket_amount} tickets for the ${event_name}
    code: |
      ${event_name}
      ${event_ticket_amount}
      Calendar.purchase_tickets(event_name=${event_name:var}, amount=${event_ticket_amount:var})
  - text: ${calendar_purchase_action} ${event_ticket_amount} tickets for the ${event_name} ${event_date_time}
    code: |
      ${event_name}
      ${event_date_time}
      ${event_ticket_amount}
      Calendar.purchase_tickets(date_time=${event_date_time:var}, event_name=${event_name:var}, amount=${event_ticket_amount:var})
  - text: ${calendar_purchase_action} ${event_ticket_amount} tickets for the ${event_name} ${event_location}
    code: |
      ${event_name}
      ${event_location}
      ${event_ticket_amount}
      Calendar.purchase_tickets(event_name=${event_name:var}, location=${event_location:var}, amount=${event_ticket_amount:var})
  - text: ${calendar_purchase_action} ${event_ticket_amount} tickets for the ${event_name} ${event_date_time} ${event_location}
    code: |
      ${event_name}
      ${event_date_time}
      ${event_location}
      ${event_ticket_amount}
      Calendar.purchase_tickets(date_time=${event_date_time:var}, event_name=${event_name:var}, location=${event_location:var}, amount=${event_ticket_amount:var})

calendar_command_query_tickets:
  - text: ${query_command_verb} if ${calendar_command_query_tickets_item}
    code: |
      ${calendar_command_query_tickets_item}
    var: ${calendar_command_query_tickets_item:var}

calendar_command_query_tickets_item:
  - text: there are tickets for ${event_name}
    code: |
      ${event_name}
      ${calendar_command_query_tickets_item:var} = Calendar.find_events_tickets(event_name=${event_name:var})
      Responder.respond(response=${calendar_command_query_tickets_item:var})
    var: event_tickets
  - text: there are tickets for ${event_name} ${event_location}
    code: |
      ${event_name}
      ${event_location}
      ${calendar_command_query_tickets_item:var} = Calendar.find_events_tickets(event_name=${event_name:var}, location=${event_location:var})
      Responder.respond(response=${calendar_command_query_tickets_item:var})
    var: event_tickets
  - text: there are tickets for ${event_name} ${event_locations}
    code: |
      ${event_name}
      ${event_locations}
      ${calendar_command_query_tickets_item:var} = []
      for location in ${event_locations:var}:
        ${calendar_command_query_tickets_item:var} += Calendar.find_events_tickets(event_name=${event_name:var}, location=location)
      Responder.respond(response=${calendar_command_query_tickets_item:var})
    var: event_tickets
  - text: there are tickets for ${event_name} ${event_location} ${event_date_time}
    code: |
      ${event_name}
      ${event_location}
      ${event_date_time}
      ${calendar_command_query_tickets_item:var} = Calendar.find_events_tickets(date_time=${event_date_time:var}, event_name=${event_name:var}, location=${event_location:var})
      Responder.respond(response=${calendar_command_query_tickets_item:var})
    var: event_tickets
  - text: there are tickets for ${event_name} ${event_location} ${event_date_times}
    code: |
      ${event_name}
      ${event_location}
      ${event_date_times}
      ${calendar_command_query_tickets_item:var} = []
      for date_time in ${event_date_times:var}:
        ${calendar_command_query_tickets_item:var} += Calendar.find_events_tickets(date_time=date_time, event_name=${event_name:var}, location=${event_location:var})
      Responder.respond(response=${calendar_command_query_tickets_item:var})
    var: event_tickets
  - text: there are tickets for ${event_name} ${event_locations} ${event_date_time}
    code: |
      ${event_name}
      ${event_locations}
      ${event_date_time}
      ${calendar_command_query_tickets_item:var} = []
      for location in ${event_locations:var}:
        ${calendar_command_query_tickets_item:var} += Calendar.find_events_tickets(date_time=${event_date_time:var}, event_name=${event_name:var}, location=location)
      Responder.respond(response=${calendar_command_query_tickets_item:var})
    var: event_tickets
  - text: there are tickets for ${event_name} ${event_locations} ${event_date_times}
    code: |
      ${event_name}
      ${event_locations}
      ${event_date_times}
      ${calendar_command_query_tickets_item:var} = []
      for location in ${event_locations:var}:
        for date_time in ${event_date_times:var}:
          ${calendar_command_query_tickets_item:var} += Calendar.find_events_tickets(date_time=date_time, event_name=${event_name:var}, location=location)
      Responder.respond(response=${calendar_command_query_tickets_item:var})
    var: event_tickets
  - text: there are tickets for ${event_name} ${event_date_time}
    code: |
      ${event_name}
      ${event_date_time}
      ${calendar_command_query_tickets_item:var} = Calendar.find_events_tickets(date_time=${event_date_time:var}, event_name=${event_name:var})
      Responder.respond(response=${calendar_command_query_tickets_item:var})
    var: event_tickets
  - text: there are tickets for ${event_name} ${event_date_times}
    code: |
      ${event_name}
      ${event_date_times}
      ${calendar_command_query_tickets_item:var} = []
      for date_time in ${event_date_times:var}:
        ${calendar_command_query_tickets_item:var} += Calendar.find_events_tickets(date_time=date_time, event_name=${event_name:var})
      Responder.respond(response=${calendar_command_query_tickets_item:var})
    var: event_tickets
  - text: there are tickets for ${event_name} ${event_date_time} ${event_location}
    code: |
      ${event_name}
      ${event_date_time}
      ${event_location}
      ${calendar_command_query_tickets_item:var} = Calendar.find_events_tickets(date_time=${event_date_time:var}, event_name=${event_name:var}, location=${event_location:var})
      Responder.respond(response=${calendar_command_query_tickets_item:var})
    var: event_tickets

schedule_command_action:
  - create ${an entry|a new entry|}
  - schedule ${an entry|a new entry|}
  - set ${an entry|a new entry|}

calendar_find_event_action:
  - find ${if there are|}
  - search ${for|}
  - look for

calendar_purchase_action:
  - buy
  - purchase
  - get
  - reserve
