reminders_query:
  - text: ${reminders_query_simple}
    code: ${reminders_query_simple}
    var: ${reminders_query_simple:var}
    type: query
  - text: ${reminders_query_command}
    code: ${reminders_query_command}
    var: ${reminders_query_command:var}
    type: query
    weight: 0.25

reminders_query_simple:
  - text: ${person_reminded_i} ${reminders_possession_verb} ${a reminder|reminders} ${reminder_content}
    code: |
      ${person_reminded_i}
      ${reminder_content}
      reminders = Reminders.find_reminders(person_reminded=${person_reminded_i:var}, content=${reminder_content:var})
      ${reminders_query_simple:var} = bool(reminders)
    var: test_reminders
    type: query
  - text: ${person_reminded_i} ${reminders_possession_verb} ${a reminder|reminders} ${reminder_contents}
    code: |
      ${person_reminded_i}
      ${reminder_contents}
      reminders = []
      for content in ${reminder_contents:var}:
        reminders += Reminders.find_reminders(person_reminded=${person_reminded_i:var}, content=content)
      ${reminders_query_simple:var} = bool(reminders)
    var: test_reminders
    type: query
  - text: ${person_reminded_i} ${reminders_possession_verb} ${a reminder|reminders} ${reminder_date_time}
    code: |
      ${person_reminded_i}
      ${reminder_date_time}
      reminders = Reminders.find_reminders(person_reminded=${person_reminded_i:var}, date_time=${reminder_date_time:var})
      ${reminders_query_simple:var} = bool(reminders)
    var: test_reminders
    type: query
  - text: ${person_reminded_i} ${reminders_possession_verb} ${a reminder|reminders} ${reminder_date_times}
    code: |
      ${person_reminded_i}
      ${reminder_date_times}
      reminders = []
      for date_time in ${reminder_date_times:var}:
        reminders += Reminders.find_reminders(person_reminded=${person_reminded_i:var}, date_time=date_time)
      ${reminders_query_simple:var} = bool(reminders)
    var: test_reminders
    type: query
  - text: ${person_reminded_i} ${reminders_possession_verb} ${a reminder|reminders} ${reminder_date_time} ${reminder_content}
    code: |
      ${person_reminded_i}
      ${reminder_date_time}
      ${reminder_content}
      reminders = Reminders.find_reminders(person_reminded=${person_reminded_i:var}, date_time=${reminder_date_time:var}, content=${reminder_content:var})
      ${reminders_query_simple:var} = bool(reminders)
    var: test_reminders
    type: query
  - text: ${person_reminded_i} ${reminders_possession_verb} ${a reminder|reminders} ${reminder_content} ${reminder_date_time}
    code: |
      ${person_reminded_i}
      ${reminder_content}
      ${reminder_date_time}
      reminders = Reminders.find_reminders(person_reminded=${person_reminded_i:var}, date_time=${reminder_date_time:var}, content=${reminder_content:var})
      ${reminders_query_simple:var} = bool(reminders)
    var: test_reminders
    type: query
  - text: ${person_reminded_i} ${reminders_possession_verb} ${a reminder|reminders} ${reminder_date_times} ${reminder_content}
    code: |
      ${person_reminded_i}
      ${reminder_date_times}
      ${reminder_content}
      reminders = []
      for date_time in ${reminder_date_times:var}:
        reminders = Reminders.find_reminders(person_reminded=${person_reminded_i:var}, date_time=date_time, content=${reminder_content:var})
      ${reminders_query_simple:var} = bool(reminders)
    var: test_reminders
    type: query
  - text: ${person_reminded_i} ${reminders_possession_verb} ${a reminder|reminders} ${reminder_content} ${reminder_date_times}
    code: |
      ${person_reminded_i}
      ${reminder_content}
      ${reminder_date_times}
      reminders = []
      for date_time in ${reminder_date_times:var}:
        reminders = Reminders.find_reminders(person_reminded=${person_reminded_i:var}, date_time=date_time, content=${reminder_content:var})
      ${reminders_query_simple:var} = bool(reminders)
    var: test_reminders
    type: query
  - text: ${person_reminded_i} ${reminders_possession_verb} ${a reminder|reminders} ${reminder_date_time} ${reminder_contents}
    code: |
      ${person_reminded_i}
      ${reminder_date_time}
      ${reminder_contents}
      reminders = []
      for content in ${reminder_contents:var}:
        reminders = Reminders.find_reminders(person_reminded=${person_reminded_i:var}, date_time=${reminder_date_time:var}, content=content)
      ${reminders_query_simple:var} = bool(reminders)
    var: test_reminders
    type: query
  - text: ${person_reminded_i} ${reminders_possession_verb} ${a reminder|reminders} ${reminder_contents} ${reminder_date_time}
    code: |
      ${person_reminded_i}
      ${reminder_contents}
      ${reminder_date_time}
      reminders = []
      for content in ${reminder_contents:var}:
        reminders = Reminders.find_reminders(person_reminded=${person_reminded_i:var}, date_time=${reminder_date_time:var}, content=content)
      ${reminders_query_simple:var} = bool(reminders)
    var: test_reminders
    type: query
  - text: ${person_reminded_i} ${reminders_possession_verb} ${a reminder|reminders} ${reminder_date_times} ${reminder_contents}
    code: |
      ${person_reminded_i}
      ${reminder_date_times}
      ${reminder_contents}
      reminders = []
      for date_time in ${reminder_date_times:var}:
        for content in ${reminder_contents:var}:
          reminders = Reminders.find_reminders(person_reminded=${person_reminded_i:var}, date_time=date_time, content=content)
      ${reminders_query_simple:var} = bool(reminders)
    var: test_reminders
    type: query
  - text: ${person_reminded_i} ${reminders_possession_verb} ${a reminder|reminders} ${reminder_contents} ${reminder_date_times}
    code: |
      ${person_reminded_i}
      ${reminder_contents}
      ${reminder_date_times}
      reminders = []
      for content in ${reminder_contents:var}:
        for date_time in ${reminder_date_times:var}:
          reminders = Reminders.find_reminders(person_reminded=${person_reminded_i:var}, date_time=date_time, content=content)
      ${reminders_query_simple:var} = bool(reminders)
    var: test_reminders
    type: query
  - text: ${person_reminded_i} ${reminders_possession_verb} ${a reminder|reminders} ${reminder_content.1} ${reminder_date_time.1} ${cc} ${reminder_content.2} ${reminder_date_time.2}
    code: |
      ${person_reminded_i}
      ${reminder_content.1}
      ${reminder_content.2}
      ${reminder_date_time.1}
      ${reminder_date_time.2}
      reminders = []
      for content in [${reminder_content.1:var}, ${reminder_content.2:var}]:
        for date_time in [${reminder_date_time.1:var}, ${reminder_date_time.2:var}]:
          reminders += Reminders.find_reminders(person_reminded=${person_reminded_i:var}, date_time=date_time, content=content)
      ${reminders_query_simple:var} = bool(reminders)
    var: test_reminders
    type: query

reminders_query_command:
  - text: ${reminders_command_find} and if there are
    code: |
      ${reminders_command_find}
      ${reminders_query_command:var} = bool(reminders)
    var: test_reminders
  - text: ${reminders_command_find} and if any in saying ${reminder_content}
    code: |
      ${reminders_command_find}
      ${reminder_content}
      ${reminders_command_find:var} = utils.filter(${reminders_command_find:var}, content=${reminder_content:var})
      ${reminders_query_command:var} = bool(reminders)
    var: test_reminders
